[package]
name = "Weylus"
version = "0.1.0"
authors = ["HMH <henry@freedesk.net>"]
edition = "2018"
description = "Use your iPad or Android tablet as graphic tablet."

[dependencies]
hyper = "^0.13"
url = "2.1.1"
tokio = { version = "0.2", features = ["full"] }
handlebars = "3.0.1"
websocket = "0.24.0"
autopilot = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2.4"
bitflags = "1.2"
image = "0.22.4"
base64 = "0.12"
mtpng = "0.3.4"
fltk = { git = "https://github.com/MoAlyousef/fltk-rs" }

[target.'cfg(not(target_os = "windows"))'.dependencies]
pnet = "0.25"

[target.'cfg(target_os = "linux")'.dependencies]
c_helper = { path = "c_helper" }

[target.'cfg(target_os = "linux")'.build-dependencies]
cc = "1.0"

[package.metadata.bundle]
name = "Weylus"
identifier = "io.github.h-m-h.weylus"

[package.metadata.deb]
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/weylus", "usr/bin/", "755"],
]
