[package]
name = "web-tablet"
version = "0.1.0"
authors = ["HMH <henry@freedesk.net>"]
edition = "2018"
description = "Use your iPad or Android tablet as graphic tablet."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "^0.13"
url = "2.1.1"
tokio = { version = "0.2", features = ["full"] }
handlebars = "3.0.1"
websocket = "0.24.0"
autopilot = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2.4"
bitflags = "1.2"
image = "0.22.4"
base64 = "0.12"
mtpng = "0.3.4"
fltk = { git = "https://github.com/MoAlyousef/fltk-rs" }
pnet = "0.25"
c_helper = { path = "c_helper" }

[target.'cfg(target_os = "linux")'.build-dependencies]
cc = "1.0"

[package.metadata.bundle]
name = "WebTablet"
identifier = "io.github.h-m-h.web-tablet"
version = "0.5"
