[package]
name = "web-tablet"
version = "0.1.0"
authors = ["HMH <henry@freedesk.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
rocket_contrib = "0.4.4"
websocket = "0.24.0"
autopilot = "0.4.0"
libc = "0.2.69"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
bitflags = "1.2"
image = "0.23"
base64 = "0.12"
mtpng = "0.3.4"
rayon = "1.3.0"

[build-dependencies]
cc = "1.0"
