[package]
name = "weylus"
version = "0.7.0"
authors = ["HMH <henry@freedesk.net>"]
license = "AGPL-3.0-or-later"
edition = "2018"
description = "Use your iPad or Android tablet as graphic tablet."

[dependencies]
hyper = "^0.13"
url = "2.1.1"
tokio = { version = "0.2", features = ["full"] }
handlebars = "3.0.1"
websocket = "0.24.0"
autopilot = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2.4"
bitflags = "1.2"
image_autopilot = { package = "image", version = "0.22.5" }
image = "0.23.5"
fltk = "^0.6"
qrcode = "0.12.0"
percent-encoding = "2.1.0"

[build-dependencies]
cc = "1.0"
num_cpus = "1.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
pnet = "0.25"

[features]
bench = []

[package.metadata.bundle]
name = "Weylus"
identifier = "io.github.h-m-h.weylus"

[package.metadata.deb]
name = "Weylus"
depends = "$auto"
section = "utility"
priority = "optional"

[profile.release]
lto = true
opt-level = 3
