[package]
name = "c_helper"
version = "1.0.0"
authors = ["HMH <henry@freedesk.net>"]
license = "AGPL-3.0-or-later"
edition = "2018"

[lib]
name = "c_helper"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "^1.0"
quote = "^1.0"

[build-dependencies]
cc = "1.0"

