name: Build

on:
  push:
    branches: [ '*' ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
        - os: ubuntu-latest
          install-deps: |
             sudo apt-get install -y libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libgl1-mesa-dev libglu1-mesa-dev libxtst-dev nasm libstdc++-6-dev gcc-6 g++-6
             sudo update-alternatives --install /usr/bin/gcc gcc $(which gcc-6) 100
             sudo update-alternatives --set gcc $(which gcc-6)
             sudo update-alternatives --install /usr/bin/g++ g++ $(which g++-6) 100
             sudo update-alternatives --set g++ $(which g++-6)
             sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 100
             sudo update-alternatives --set cc /usr/bin/gcc
             sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 100
             sudo update-alternatives --set c++ /usr/bin/g++
             g++ --version
             gcc --version
             cargo install cargo-deb
          build-cmd: cargo deb
          package-files: |
             target/release/linux.zip
             target/debian/Weylus*.deb
          pkg-cmd: cd target/release/ && zip linux.zip weylus

        - os: macOS-latest
          install-deps: |
             npm install -g typescript
             brew install nasm
             cargo install cargo-bundle
          build-cmd: cargo bundle --release
          package-files: target/release/bundle/osx/macOS.zip
          pkg-cmd: cd target/release/bundle/osx/ && zip -r macOS.zip Weylus.app

        - os: windows-latest
          install-deps: |
             curl -LO https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip
             7z x nasm-2.14.02-win64.zip
             cp nasm-2.14.02/nasm.exe /usr/bin/nasm.exe
             npm install typescript
          build-cmd: cargo build --release --verbose
          package-files: target/release/Windows.zip
          pkg-cmd: cd target/release/ && 7z a Windows.zip weylus.exe

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: deps/dist
        key: ${{ runner.os }}-deps-${{ hashFiles('deps/*') }}-1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-1
    - name: Download deps
      run: ${{ matrix.install-deps }}
      shell: bash
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: ${{ matrix.build-cmd }}
      shell: bash
    - name: Package
      run: ${{ matrix.pkg-cmd }}
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            ${{ matrix.package-files }}
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
