name: Build

on:
  push:
    branches: [ '*' ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
        - os: ubuntu-latest
          build-cmd: npm install -g typescript && cargo install cargo-deb && cargo deb
          package-files: |
             target/release/linux.zip
             target/debian/Weylus*.deb
          pkg-cmd: cd target/release/ && zip linux.zip weylus
        - os: macOS-latest
          build-cmd: npm install -g typescript && cargo install cargo-bundle && cargo bundle --release
          package-files: target/release/bundle/osx/macOS.zip
          pkg-cmd: cd target/release/bundle/osx/ && zip -r macOS.zip Weylus.app
        - os: windows-latest
          build-cmd: npm install -g typescript && npm run build && cargo build --release --verbose
          package-files: target/release/Windows.zip
          pkg-cmd: cd target/release/ && 7z a Windows.zip weylus.exe

    steps:
    - name: Download deps
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install -y libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libxtst-dev
         fi
      shell: bash
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Build
      run: ${{ matrix.build-cmd }}
    - name: Package
      run: ${{ matrix.pkg-cmd }}
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            ${{ matrix.package-files }}
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
